export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS"
export const CREATE_USER_FAIL = "CREATE_USER_FAIL"

export const LIST_USER_SUCCESS = "LIST_USER_SUCCESS"
export const LIST_USER_FAIL = "LIST_USER_FAIL"

export const SHOW_USER_SUCCESS = "SHOW_USER_SUCCESS"
export const SHOW_USER_FAIL = "SHOW_USER_FAIL"

export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS"
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL"

export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS"
export const DELETE_USER_FAIL = "DELETE_USER_FAIL"

export const DELETE_ALL_USER_SUCCESS = "DELETE_ALL_USER_SUCCESS"
export const DELETE_ALL_USER_FAIL = "DELETE_ALL_USER_FAIL"

export const SEARCH_USER_SUCCESS = "SEARCH_USER_SUCCESS"
export const SEARCH_USER_FAIL = "SEARCH_USER_FAIL"